name: Build DEB

on:
  push:
    branches: [ main ]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper dh-python python3-all python3-setuptools python3-pip fakeroot

      - name: Prepare debian metadata
        run: |
          VERSION=$(python setup.py --version)
          echo "Detected version: $VERSION"
          mkdir -p debian
          cat > debian/control <<'EOF'
          Source: dnsblchk
          Section: utils
          Priority: optional
          Maintainer: DNSBL Checker <contact@example.com>
          Build-Depends: debhelper-compat (= 13), python3, python3-setuptools, dh-python
          Standards-Version: 4.6.0
          Homepage: https://github.com/example/dnsblchk

          Package: dnsblchk
          Architecture: all
          Depends: ${python3:Depends}, ${misc:Depends}
          Description: DNS Blacklist Checker service
           Monitors IPs against DNSBLs and can email alerts.
          EOF
          echo '13' > debian/compat
          cat > debian/rules <<'EOF'
          #!/usr/bin/make -f
          %:
          	dh $@ --with python3 --buildsystem=pybuild
          EOF
          chmod +x debian/rules
          cat > debian/install <<'EOF'
          dnsblchk.service usr/lib/systemd/system/
          config/config.yaml.template etc/dnsblchk/config.yaml
          EOF
          cat > debian/changelog <<EOF
          dnsblchk ($VERSION-1) unstable; urgency=medium
            * Automated build.
           -- DNSBL Checker <contact@example.com>  $(date -u '+%a, %d %b %Y %H:%M:%S +0000')
          EOF

      - name: Build DEB package
        run: |
          dpkg-buildpackage -us -uc -b

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ../dnsblchk_*_all.deb
